name: C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake --preset default

      - name: Build project
        run: cmake --build --preset default

      - name: Run unit tests
        run: build/default/src/fem_tests src/data/